version: "3"
services:
  jenkins:
    container_name: jenkins_managed_by_compose
    image: jenkins:ansible
    ports:
      - "8081:8080"
      - "50001:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /home/kali/ansible-playbooks/:/var/jenkins_home/workspace/ansible
      - /etc/ansible/:/etc/ansible/
    restart: always
    networks:
      - net_jenkins
volumes:
  jenkins_home:
networks:
  net_jenkins: